repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [--verbose]
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff-check
        name: ruff-isort
        args: ["--select", "I", "--fix"]
      - id: ruff-check
        name: ruff-docformatter
        args: ["--select", "D", "--ignore", "D202", "--fix-only", "--fix"]
      # - id: ruff-check # linter but not fixing issues
  - repo: local
    hooks:
      - id: make-docs
        name: make-docs
        entry: bash -c 'make docs'
        language: system
        types: [file]
        files: ^(src\/|README\.md$)
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.4.2
    hooks:
      # - id: sqlfluff-lint
      - id: sqlfluff-fix
default_install_hook_types: [pre-commit, commit-msg]
# default_language_version:
#     python: python3.12
