# Ideally the rev should match the package version in the environment
repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [--verbose]
  - repo: https://github.com/crate-ci/typos
    rev: v1.50.1
    hooks:
      - id: typos
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.5.1
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.6
    hooks:
      - id: ruff-check
        name: ruff-isort
        args: ["--select", "I", "--fix"]
      - id: ruff-check
        name: ruff-docformatter
        args: ["--select", "D", "--ignore", "D202", "--fix-only", "--fix"]
      - id: ruff-check
        name: ruff-check
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
  - repo: https://github.com/reteps/dockerfmt
    rev: v0.5.4
    hooks:
      - id: dockerfmt
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 4.3.0
    hooks:
      # - id: sqlfluff-lint
      - id: sqlfluff-fix
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: prettier --write
        language: system
        files: \.(json|jsonc|md|ya?ml)$
      - id: taplo
        name: Auto-format TOML files with taplo
        entry: taplo format
        language: python
        additional_dependencies: ["taplo == 0.9.3"]
        types: [toml]
      - id: shfmt
        name: Auto-format shell scripts with shfmt
        entry: shfmt -w
        language: system
        types: [shell]
      # - id: stan-format
      #   name: Auto-format Stan files with stanc
      #   entry: scripts/stanc_format.sh
      #   language: system
      #   files: \.stan$
      - id: make-docs
        name: make-docs
        entry: bash -c 'make docs'
        language: system
        types: [file]
        files: ^(src\/|README\.md$)
default_install_hook_types: [pre-commit, commit-msg]
# default_language_version:
#     python: python3.12
